name: "AWS Deploy workflow"

on:
  pull_request:
    branches: [dev]
    types: [closed]

permissions:
  id-token: write

jobs:
  aws:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: aws cli configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_MWO }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_MWO }}
          aws-region: "us-east-1"

      - name: configure sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: install deps
        run: |
          npm run install

      - name: "sam build and deploy"
        run: |
          npm run package:deploy
