name: "AWS Deploy workflow"

on:
  push:
    branches: [dev]

permissions:
  id-token: write

jobs:
  aws:
    if: true
    runs-on: ubuntu-latest

    steps:
      - name: branch checkout
        uses: actions/checkout@v3

      - name: aws cli configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_MWO }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_MWO }}
          aws-region: "us-east-1"

      - name: configure sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: clean install deps
        run: |
          npm ci

      - name: "sam build and deploy"
        run: |
          echo "NODE_ENV=github_actions" >> GITHUB_ENV
          npm run package-deploy
          # NODE_ENV=github_actions npm run package-deploy
          # you can also set NODE_ENV with env directive above before running npm
          # or append env setter into $GITHUB_ENV
          # run echo "NODE_ENV=github_actions" >> $GITHUB_ENV
