name: "AWS Deploy workflow"

on:
  pull_request:
    branches: [dev]
    types: [closed]

permissions:
  id-token: write

jobs:
  aws:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH_NAME: ${{ github.base_ref }}

    steps:
      - name: branch checkout
        uses: actions/checkout@v3

      - name: aws cli configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_MWO }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_MWO }}
          aws-region: "us-east-1"

      - name: configure sam
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: clean install deps
        run: |
          npm ci

      - name: "set env vars"
        run: |
          filename="sam-configs/$TARGET_BRANCH_NAME"
          while IFS= read -r item; do
              # echo "$item"
              echo "$item" >> $GITHUB_ENV
          done < "$filename"

      - name: "sam build and deploy"
        run: |
          # NODE_ENV=github_actions npm run package-deploy # ditching npm

          npm run build
          sam build --template ./sam-template.yaml
          sam deploy --stack-name $CFN_STACK_NAME --capabilities CAPABILITY_IAM --s3-bucket $S3_BUCKET --region $AWS_REGION
