name: "Test workflow"
on:
  pull_request:
    branches: [dev__DISABLED]

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-node
        uses: actions/setup-node@v3

      - name: install deps
        run: |
          npm install

      - name: run test
        run: |
          npm run test
